GET http://localhost:3000/users

###

GET http://localhost:3000/users/b4037141-dc2a-44f5-9d52-a0ec80d6af09

###

POST http://localhost:3000/users/
Content-Type: application/json

{
    "name": "Alfie",
    "email": "alf.fred@gmail.com",
    "pw": "freddy331"
}

###

DELETE http://localhost:3000/users/6ed89092-3ce0-40f1-88a1-2915600c630e

###
PATCH http://localhost:3000/users/82048194-e36e-44ac-ad29-6c0b966ed1bb
Content-Type: application/json

{
    "pw": "freddy331"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "alf.fred@gmail.com",
    "password": "freddy331"
}

###

GET http://localhost:3000/auth/test

###

PATCH http://localhost:3000/users/passwordUpdate/e6a06e2f-2e11-4f50-9db5-f009dfecb732
Content-Type: application/json

{
    "pw": "freddy331"
}